version: 0.2
phases:
  install:
    runtime-versions: 
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm install
      - npm install -g @angular/cli@16.2.3
  build:
    commands:
     - echo "Building Angular Project"
     - ng build
  post_build:
    commands:
     - echo "Updating files in S3"
     - aws s3 sync dist/angular-primeng-app/ s3://easyrent-frontend --delete