version: '3'
services:
  simplerent_frontend:
    container_name: simplerent_frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend_server/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s