name: Deploy to Web Server

on:
    # push:
    #     branches: [ main ]
    # pull_request:
    #     branches: [ main ]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
                node-version: '18'
                cache: 'npm'
        
        - name: Install dependencies
          run: npm ci
        
        - name: Build application
          run: npm run build
        
        - name: Deploy to server
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
                cd /var/www/html
                git pull origin main
                npm install --production
                npm run build
                sudo systemctl restart nginx