package com.example.deploydemo.service.security;

public enum Permission {

    OWNER_SPECIFIC_PERM,
    ADMIN_SPECIFIC_PERM,
    TENANT_SPECIFIC_PERM,
    SEMI_PERM,


    APARTMENTS_READ,
    APARTMENTS_CREATE,
    APARTMENTS_DELETE,

    RENT_CONTRACT_READ,
    RENT_CONTRACT_CREATE,
    RENT_CONTRACT_DELETE,

    CONTRACT_READ,
    CONTRACT_CREATE,
    CONTRACT_DELETE,

    RENT_PROPERTY_PHOTO_READ,
    RENT_PROPERTY_PHOTO_CREATE,
    RENT_PROPERTY_PHOTO_DELETE,

    TENANT_READ,
    TENANT_CREATE,
    TENANT_DELETE,

    APPEAL_READ,
    APPEAL_CREATE,
    APPEAL_UPDATE,
    APPEAL_DELETE,

    ANNOUNCEMENT_READ,
    ANNOUNCEMENT_CREATE,
    ANNOUNCEMENT_DELETE,

    TENANT_USER_CREATE,
    TENANT_USER_UPDATE,
    OWNER_USER_CREATE,
    OWNER_USER_UPDATE
}
